title: ANKEALcode
logo: /assets/img/logo-480.png
description: Web Design & Website Development.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
gem "github-pages", group: :jekyll_plugins
